<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_bi bi-person-circle fs-3 mr-3</name>
   <tag></tag>
   <elementGuidId>94960530-0bfb-42c4-be32-7acc4f7e6ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-person-circle.fs-3.mr-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ef7be12b-b732-4f44-9dfb-01d3fa0866de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-person-circle fs-3 mr-3</value>
      <webElementGuid>e49a121d-800b-415e-9a84-4ae58c36f133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main&quot;]/nav[@class=&quot;navbar navbar-expand px-3 border-bottom&quot;]/div[@class=&quot;ms-auto&quot;]/a[@class=&quot;position-relative d-inline-block&quot;]/i[@class=&quot;bi bi-person-circle fs-3 mr-3&quot;]</value>
      <webElementGuid>0f30c8c9-e1f7-4b15-b42c-bce754819725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>75f65d88-6a83-49cf-80fd-a0d273c15b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
