<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin Login</name>
   <tag></tag>
   <elementGuidId>646519ce-a01b-4fd7-9963-15b3cd5302aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.admin-login-mobile.btn1.adminlogbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;document.getElementById('myModal').style.display='flex'&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Admin Login&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b825c8e5-7d29-42dc-8e6a-f4e68b2e19f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link admin-login-mobile btn1 adminlogbtn</value>
      <webElementGuid>b8d3d965-d015-4a06-97b3-b504d73b0f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('myModal').style.display='flex'</value>
      <webElementGuid>b3148d45-f63f-46ac-99f7-108d7a570ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Login</value>
      <webElementGuid>edf16009-947e-4469-ac44-338fe6b10004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;head navbar navbar-expand-lg navbar-dark bg-primary&quot;]/div[@class=&quot;container&quot;]/a[@class=&quot;nav-link admin-login-mobile btn1 adminlogbtn&quot;]</value>
      <webElementGuid>ab456dc7-44c0-4fb5-9c54-3308ddf2104d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;document.getElementById('myModal').style.display='flex'&quot;]</value>
      <webElementGuid>b27b7e39-8d7d-48d4-80c6-4c1b6dc0403c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin Login')]</value>
      <webElementGuid>fa5ef4f1-cdf8-475a-8e55-9ee1cf622e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ArtLens'])[2]/following::a[1]</value>
      <webElementGuid>79995f23-064f-481e-9de4-a690807d1725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[1]</value>
      <webElementGuid>a40c09f9-84a8-4086-a3f9-f632694cdb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARTLENS'])[1]/preceding::a[1]</value>
      <webElementGuid>1ede1742-0c26-44c5-87ef-bfcfa201d47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Login']/parent::*</value>
      <webElementGuid>403ab51c-8b0e-4a9c-aeb1-f2a838544a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>91ae06c7-921a-463b-834b-00c1433568a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Admin Login' or . = 'Admin Login')]</value>
      <webElementGuid>ec35b3ac-e04c-45bc-9e31-ef229f381816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
